### PR TITLE
Skip today

### PR DESCRIPTION
**Pull request by BMStroh**
Added command line option to skip today's Daily Note file when running - my script to add headers based on my daily calendar was being undone when npTools ran and removed empty headings before the meetings happened and I had any notes.

### CODE REVIEW

**Comment by BMStroh** [comment]
I should have updated and checked in the doc file to reflect this, which I realized well after the fact.  If you choose to merge this, I'm happy to provide that update as well.

**Review by jgclark — CHANGES_REQUESTED** [review]
Good work, thank you. Ready to approve if you can also update the README.

**Comment by BMStroh** [comment]
Added the command line info for --skiptoday.

Note that there's an undocumented change here as well - I sorted the notes before processing so they'd be in order in the log.

**Comment by jgclark** [comment]
Thanks, @BMStroh. Merged.

**Pull request merged**
